version: '3'

services:
  node1:
    image: funkypenguin/marcoin
    container_name: marcointest-node1
    volumes:
      - ../marcoind:/var/lib/marcoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/marcoin
#    container_name: marcointest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/marcoin
#    container_name: marcointest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

